apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "rag-logs-*"
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: elasticpassword
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.12.2"
    editable: false
